# figstyle default

width: 160e-3

ratio:
 - 1
 - .6

hspace: .1

colors:
 - '#ffa366'
 - '#80bfff'
 - '#79ff4d'
 - '#ff99cc'
 - '#8585ad'
 - '#cccc00'
 - '#00802b'
 - '#ff0000'
 - '#0000aa'
 - '#ff00ff'

markers:
 - '.'
 - 's'
 - 'p'
 - 'X'
 - '^'
 - 'D'

main_color: '#888888'
